name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      javaVersion:
        description: 'Java version'
        required: true
        default: 8
      minecraftVersion:
        description: 'Minecraft version'
        required: true
      forgeVersion:
        description: 'Forge version'
        required: true
        default: '14.23.5.2854'
      name:
        description: 'Modpack name'
        required: true
      version:
        description: 'Modpack version'
        required: true
      downloadUrl:
        description: 'Modpack server download url'
        required: true

jobs:
  build:
    env:
      JAVA_VERSION: ${{ github.event.inputs.javaVersion }}
      MINECRAFT_VERSION: ${{ github.event.inputs.minecraftVersion }}
      FORGE_VERSION: ${{ github.event.inputs.forgeVersion }}
      PACK_NAME: ${{ github.event.inputs.name }}
      PACK_VERSION: ${{ github.event.inputs.version }}
      DOWNLOAD_URL: ${{ github.event.inputs.downloadUrl }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build . \
            -t curseforge/${PACK_NAME}:${PACK_VERSION} \
            --build-arg JAVA_VERSION \
            --build-arg MINECRAFT_VERSION \
            --build-arg FORGE_VERSION \
            --build-arg PACK_NAME \
            --build-arg PACK_VERSION \
            --build-arg DOWNLOAD_URL

      - name: Push to docker hub
        run: docker push curseforge/${PACK_NAME}:${PACK_VERSION}
