name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Modpack version'
        required: true
      downloadUrl:
        description: 'Modpack server download url'
        required: true

jobs:
  build:
    env:
      JAVA_VERSION: 8
      MINECRAFT_VERSION: 1.12.2
      FORGE_VERSION: 14.23.5.2854
      PACK_NAME: RLCraft
      PACK_VERSION: ${{ github.event.inputs.version }}
      DOWNLOAD_URL: ${{ github.event.inputs.downloadUrl }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: curseforge/${{ env.PACK_NAME }}:${{ env.PACK_VERSION }}
          build-args: |
            JAVA_VERSION
            MINECRAFT_VERSION
            FORGE_VERSION
            PACK_NAME
            PACK_VERSION
            DOWNLOAD_URL
